apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: was
  template:
    metadata:
      labels:
        app: was
    spec:
      containers:
      - name: tomcat
        image:  851557167064.dkr.ecr.ap-northeast-2.amazonaws.com/demo-maven-springboot:50
